version: '{build}'
image: Visual Studio 2015
nuget:
  disable_publish_on_pr: true
build_script:
- ps: ./build -Target Publish
test: off
deploy:
- provider: Environment
  name: Tempest | MyGet
  on:
    branch: develop